//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daybi2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Курсовая
    {
        public int ID { get; set; }
        public int Ключ_студента { get; set; }
        public string Курсовая1 { get; set; }
        public int Оценка_курсовой { get; set; }
        public string Проект { get; set; }
        public int Оценка { get; set; }
    }
}
