//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daybi2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оценки
    {
        public int ID { get; set; }
        public int Ключ_преподователя { get; set; }
        public int Ключ_предмета { get; set; }
        public int Ключ_студента { get; set; }
        public System.DateTime Дата { get; set; }
        public int Итоговые_оценки { get; set; }
    }
}
