//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daybi2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты
    {
        public int ID { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int Номер_пасспорта { get; set; }
        public int Ключ_группы { get; set; }
        public int Ключ_перв { get; set; }
        public System.DateTime Дата_рождения { get; set; }
    }
}
